<?php
/**
 * Groupclone Product
 * 
 * @category   Design
 * @package    default_greytheme
 * @copyright  Copyrights 2014 by Contus. (http://www.contus.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$this->license = Mage::registry('license1');
if($this->license == '')
{
     Mage::register('license1', Mage::getModel('deal/deal')->isLicense());
     $this->license = Mage::registry('license1');
}
if ($this->license  === true) {
$productIds = Mage::getSingleton('core/session')->getProductIds();
}
$productId = $productIds[0];
$dealsCity = Mage::getModel('deal/deal')->fetchCity();
$model = Mage::getModel('catalog/product'); //getting product model
$_product = $model->load($productId); 
$dealCity = str_split($_product->getDealcity()); 
$dealstatus = $_product->getStatus(); 
$flag =0;
if(in_array($dealsCity,$dealCity)){

    $flag=1;
}
else{
    $flag =0;
}
if (empty($productIds)|| $dealstatus ==2) {
?>
    <div class="contpad clearfix">
        <div class="nodealtext clearfix ">  <?php echo "<h1>" . $this->__('No Deal Available') . "</h1>" ?></div>
    </div>
<?php
    }
 else {
?>
    <script type="text/javascript">
        <!--
        var j =1;
        if (typeof(BackColor)=="undefined")
            BackColor = "white";
        if (typeof(ForeColor)=="undefined")
            ForeColor= "black";
        if (typeof(DisplayFormat)=="undefined")
            DisplayFormat = "<span class='time_item day'><span class='number'>%%D%%</span><br/>DAYS</span><span class='time_item hour'><span class='number'>%%H%%</span><br/>HOURS</span> <span class='spacer_time'>:</span> <span class='time_item min'><span class='number'>%%M%%</span><br/>MINUTES</span> <span class='spacer_time'>:</span> <span class='time_item sec'><span class='number'>%%S%%</span><br/>SECONDS</span>";
        if (typeof(CountActive)=="undefined")
            CountActive = true;
        if (typeof(FinishMessage)=="undefined")
            FinishMessage = "";
        if (typeof(CountStepper)!="number")
            CountStepper = -1;
        if (typeof(LeadingZero)=="undefined")
            LeadingZero = true;
        CountStepper = Math.ceil(CountStepper);
        if (CountStepper == 0)
            CountActive = false;
        var SetTimeOutPeriod = (Math.abs(CountStepper)-1)*1000 + 990;
        function calcage(secs, num1, num2) {
            if(num1==3600){s = ((Math.floor(secs/num1)) - (num2 * 24)).toString();}
            else{s = ((Math.floor(secs/num1)%num2)).toString();}
            if (LeadingZero && s.length < 2)
                s = "0" + s;
            return s;
        }
        function CountBack(secs,iid,j) {
            if (secs < 0) {
                
            
                document.getElementById(iid).innerHTML = FinishMessage;
                var dealimage = "<?php echo $this->getSkinUrl('images/8.png') ?>";
                var buynowreplace = "<?php echo $this->getSkinUrl('images/deal-closed.png') ?>";
                document.getElementById('deal_status-'+j).innerHTML ='<div class="clsstatus">Deal closed !</div> ';
                document.getElementById('viraiterbg').style.display = "none";
                document.getElementById('scriptbuynow-'+j).innerHTML ='<img src="'+buynowreplace+'"  alt="deal closed" title="deal closed"/>';
                document.getElementById('scriptbuynow-'+j).setAttribute('href', '#!');
                document.getElementById('scriptbuynow-'+j).setAttribute('onclick', '#');
                document.getElementById('script_gift_box'+j).style.display = "none";            
                return;
            }
            var days = calcage(secs,86400,100000);

            if(days == 00) {
                DisplayStr = DisplayFormat.replace(/%%D%%/g, '<span class="nodays"></span>');
            } else {
                DisplayStr = DisplayFormat.replace(/%%D%%/g, calcage(secs,86400,100000));
            }
            DisplayStr = DisplayStr.replace(/%%H%%/g, calcage(secs,3600, days));
            DisplayStr = DisplayStr.replace(/%%M%%/g, calcage(secs,60,60));
            DisplayStr = DisplayStr.replace(/%%S%%/g, calcage(secs,1,60));
            document.getElementById(iid).innerHTML = DisplayStr;
            if (CountActive)
                setTimeout(function(){CountBack((secs+CountStepper),iid,j)}, SetTimeOutPeriod);
        }
        //-->
    </script>
<?php
    $count = 1;
$productQuantiy = (int) Mage::getModel('cataloginventory/stock_item')->loadByProduct($productId)->getQty();
?>
        <div class="col-main" style="position: relative;">
            <div class="page-title">
                <?php               
                $dealstatus = $_product->getDealStatus();
                 $_gallery = $_product->getMediaGalleryImages();
                $product = $this->getProduct();
    /** @var $coreResource Mage_Core_Model_Resource */
$coreResource = Mage::getSingleton('core/resource');
 
/** @var $conn Varien_Db_Adapter_Pdo_Mysql */
$conn = $coreResource->getConnection('core_read');
 
/** @var $select Varien_Db_Select */
$select = $conn->select()
    ->from(array('p' => $coreResource->getTableName('videoupload')), new Zend_Db_Expr('entity_id,thumname,videoupload_id'))
    
    ->where('p.status = ?',1)
    ->where('p.entity_id = ?',$productId);
 
    $videoDetails = $conn->fetchALL($select);
                $videoId = ''; 
                foreach ($videoDetails as $videoDetail)
                {
                	 $thumbName = $videoDetail['thumname'];
                     $productId = $videoDetail['entity_id'];
                     $videoId = $videoDetail['videoupload_id'];            	
                }
               ?>
                <div class="top_heading" style="margin">
                <h1><?php echo $this->htmlEscape($_product->getName()) ?></h1>
                </div>
			<fieldset class="no-display">
				<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
			</fieldset>
            <div class="right_column">
			<span class="sub_tittle"><?php echo $this->htmlEscape($_product->getSubtitle()) ?></span><br/>
			<?php
			if($_product->getSpecialPrice()) {
				$sp_price = $_product->getSpecialPrice();
			} else {
				$sp_price = $_product->getPrice();
			}?>
			<div><span style="font-size: 25px;margin-right:10px;"><sup><?php echo $this->__('NOW'); ?></sup></span> <b style="font-size: 40px; color:#d96709;" id="price_value-<?php echo $count; ?>" class="discounted-price"> <?php echo Mage::helper('core')->currency($sp_price, true);  ?> </b> <span style="font-size:18px;margin-left:10px;text-decoration: line-through;color: #888;">Before: <span id="value_box_span"><?php echo Mage::helper('core')->currency($_product->getPrice(), true, true) ?></span></span></div>
			                            <!--Time box-->
            <?php
				//product's regular Price
				$todayDate = Mage::getModel('catalog/product')->getResource()->formatDate($_product->getspecial_to_date(), false);
				$expirydate = $todayDate . ' ' . $_product->gettime();
            ?>

            <?php  if($productQuantiy != '' || $productQuantiy != 0) { ?>
					<div class="timerbg_middle clearfix" style="border:none;">
					<h3 style="text-align:center;color:#ff3030;font-size:22px;margin-top: -8px;">TIME LEFT TO BUY</h3>
						<span class="corner_img"></span>
						<div class="deal_statusnew" >
							<div class="timerbox" >
							  <div class="viraiterbg" id="viraiterbg">
									<div id="countbox_<?php echo $count; ?>" class="cntdwn"></div>
								</div>
								<div class="deal_status" id ="deal_status-<?php echo $count; ?>"></div>
							</div>
						</div>
					</div>
            <?php } ?>
			<div class="clear"></div>
			<div class="buy_edge">
					<?php   if($productQuantiy!=  '' || $productQuantiy != 0) { ?>
						<?php if($_product->getOptions()) { ?>                                
								<a onclick="showCustomoptions();" href='JavaScript:void(0);' id="scriptbuynow-<?php echo $count; ?>" class="buynowbtn see_option"><?php echo $this->__("See Options") ?></a>                                
						<?php } else { ?>
								<?php if($sp_price !=0){ ?>
								<a href='<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>' id="scriptbuynow-<?php echo $count; ?>" class="buynowbtn"><?php echo $this->__("BUY NOW!") ?><span class="buy_arrow"></span></a>
								<?php } else { ?>
								 <a href='<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>' id="scriptbuynow-<?php echo $count; ?>" class="buynowbtn"><?php echo $this->__("Free!") ?><span class="buy_arrow"></span></a>
						<?php } }?>
				<?php } else { ?>
				<span class="sold_out">Sold Out</span>
				<?php } ?>
			</div>
			<div class="clear"></div>
			<div style="width:50%;float:left;margin-top:10px;">
			<div class="gift_box clearfix" id ="script_gift_box<?php echo $count; ?>">
			<i></i>
			<div class="buy_friend">
				<?php
					if (!Mage::getSingleton('customer/session')->isLoggedIn()) {  // if not logged in
							Mage::getSingleton('customer/session')->setBeforeAuthUrl($this->helper('checkout/cart')->getAddUrl($_product));
							//redirect to login page
							$url = Mage::getBaseUrl() . "customer/account/login/";
							?>
					<a href="<?php echo $url; ?>" class="clsbuyfriend" ><?php echo $this->__('Give as a gift'); ?></a>
					<?php } else { ?>
					<form name="gift<?php echo $count; ?>" method="post" action="<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>">
						<fieldset>
							<input type="hidden" name="giftoption" value="gift" />                                           
							<a onclick="javascript:document.gift<?php echo $count; ?>.submit()" class="clsbuyfriend" ><?php echo $this->__('Give as a gift'); ?></a>
						</fieldset> 
					</form>
					<?php } ?>
				</div>
			</div>
			</div>
			<div style="width:40%;float:left;margin-top:10px;padding-left: 30px;">
			   <div class="spread clearfix">
					<h3>Share This Deal:</h3>
                    <?php
                                // Prepare URL for the facebook dialog feed.
                                $appId = Mage::getStoreConfig('customer/facebook/api_id');
                                $baseUrl = Mage::getBaseUrl();
   $productUrl = $baseUrl.$_product->getUrlPath(); 
    $redirectUrl = Mage::getBaseUrl();
                                $productImage = $this->helper('catalog/image')->init($_product, 'image');
                                $productName = urlencode($_product->getName());
                                $productDescription = urlencode(strip_tags($_description));
                                $fbUrl = 'http://www.facebook.com/dialog/feed?app_id=' . $appId . '&amp;description=' . $productDescription . '&amp;picture=' . $productImage . '&amp;name=' . $productName . '&amp;message=&amp;redirect_uri=' . $redirectUrl . '&amp;link=' . $productUrl;
                                 $twitterurl = 'http://twitter.com/share?text='.$productName.'&amp;redirecturl=' .  $redirectUrl;
                    ?>
                                <span class="sharelinks">
                                    
                                <script type="text/javascript">
                             $j('.popup').click(function(event) {
                                var width  = 575,
                                    height = 400,
                                    left   = ($(window).width()  - width)  / 2,
                                    top    = ($(window).height() - height) / 2,
                                    url    = this.href,
                                    opts   = 'status=1' +
                                             ',width='  + width  +
                                             ',height=' + height +
                                             ',top='    + top    +
                                             ',left='   + left;

                                window.open(url, 'twitte', opts);

                                return false;
                              });</script>
                        <?php
                        
                                $baseUrl = Mage::getBaseUrl();
                                $productUrl = $baseUrl.$_product->getUrlPath();
                                $mailBody = $_description . '<br/> Url : ' . $productUrl;
                                $mail = "mailto:?body=" . htmlspecialchars(strip_tags($mailBody)) . " &amp;subject=" . $_product->getName();
                        ?>
                                 <a class="social_link mail_link" title="Share with email" href="<?php echo $mail; ?>" ></a>
                                 <a class="social_link facebook_link" title="Share with facebook" href="<?php echo $fbUrl; ?>" target="_blank"></a>
                                 <a class="social_link twitter_link"  title="Share with twitter" href="<?php echo $twitterurl; ?>" target="_blank"></a>
                                 <a class="social_link pin-it-button"  title="Pinterest Share" href="http://pinterest.com/pin/create/button/?url=<?php echo $productUrl; ?>&amp;media=<?php echo $productImage;?>&amp;description=<?php echo $_product->getName(); ?>"  target="_blank"> </a>                                 
                            </span>
                        </div>
				</div>
		</div>
        <div class="left_column">
		  <div id="featured-<?php echo $count; ?>" <?php echo $displayImage; ?> >
                <div class="banner_middle"  id='image-<?php echo $count; ?>'>
                <?php if (count($_gallery) > 1) {
                    foreach ($_gallery as $_image): ?>
                                <?php $imageSrc = $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>
                                <img src="<?php echo $imageSrc ?>" width="460" height="279" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"  />
                    <?php endforeach; ?>

                <?php } else { ?>
                                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" width="460" height="279" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"  />
                <?php } ?>
                </div>
            </div>                            
            <?php if (count($_gallery) > 1) { ?>
                    <script type="text/javascript">
                        <!--
                        $j('#featured-<?php echo $count; ?>').orbit({
                            'bullets': true,
                            'bulletid': <?php echo $count; ?>,
                            'timer' : true,
                            'animation' : 'fade',
                            'captions' : false,
                            'directionalNav' : false
                        });
                        //-->
                    </script>
            <?php } ?>
			<?php
                    if($_product->getSpecialPrice()) {
                    $discount_price = $_product->getPrice() - $_product->getSpecialPrice();
                    $discount = ($discount_price * 100) / $_product->getPrice();
                    $discount = round($discount);
                    } else {
                        $discount_price = 0;
                        $discount = 0;
                    }
			?>
			<div class="discount-boxes clearfix" >                       
				<div class="clsdiscount_prices" id="value_box">
					<span><?php echo $discount . '%'; ?></span>
					<h3><?php echo $this->__('Discount'); ?></h3>
				</div>
				<div class="clsdiscount_prices" id="discount_box">
            <?php
			if (!$_product->isGrouped()) {
				$resultQuantity = $this->getQuantityPurchase($_product);
			}
			if($productQuantiy != '' || $productQuantiy != 0) { ?>
					<div class="totalcount"><?php  if($_product->gettarget_number() != 0) { if($resultQuantity[0] > $_product->gettarget_number()) echo $this->__('Over'); } ?> <?php echo $resultQuantity[0]; ?></div>
<!--                                   <div class="deal_status" id ="deal_status-<?php echo $count; ?>">
					<?php   if($_product->gettarget_number() != 0) { ?>
							<div class="clsstatus"><?php echo $this->__($resultQuantity[2]); ?></div>
						<?php } ?>
					</div>-->
			<?php } else { ?>
					<div class="totalcount"></span> <?php echo $this->__('Deal Sold Out'); ?></div>
<!--                                    <div class="deal_status" id ="deal_status-<?php echo $count; ?>">
							<img src="<?php echo $this->getSkinUrl('images/8.png') ?>"  width="180" height="16" alt="Rate" title="Rate"  class="statusimg"/>
						<div class="clsstatus"><?php echo $this->__('Better luck next time'); ?></div>
					</div>-->
			<?php } ?>
				<span></span>
				<h3><?php echo $this->__('Purchased'); ?></h3>
				</div>
				<div class="clsdiscount_prices" id="save_box">
					<span id="save_box_span"><?php echo $productQuantiy; ?></span>
					<h3><?php echo $this->__('Remaining'); ?></h3>
				</div>
				
				<!-- Value box will disappear when digits exceed 7 -->                         
				<script type="text/javascript">
					value_width=document.getElementById('value_box_span').offsetWidth;
					save_width=document.getElementById('save_box_span').offsetWidth;
					if( (save_width>73)||(value_width>73) ){
					   document.getElementById('value_box').style.display='none';
					   document.getElementById('discount_box').style.width = "40%";
					   document.getElementById('save_box').style.width = "60%";
					}
				</script>                     
            </div>
			</div>
                        <script type="text/javascript">
                            <!--

                            var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y h:i:s A", strtotime($expirydate)); ?>");
                            start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage::getModel('core/date')->date('Y-m-d H:i:s'))); ?>";
                            start_date = Date.parse(start);
                            var dnow<?php echo $count; ?> = new Date(start_date);
                            if(CountStepper>0)
                                ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
                            else
                                ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
                            gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);

                            var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
                            CountBack(gsecs<?php echo $count; ?>,"countbox_"+j, j);
                            j++;
                            //-->
                        </script>
                        <!--End of Time box-->
                </div>
				
                <!--left content-->
                <div class="clear"></div>
				<div class="products-tabs">
				
				</div>
                <!--contpad-->
                <div class="reviewbox" id="review-<?php echo $count; ?>">
                                <div class="col-main col-pad-bottom">
                        <?php if ($renderDescription) : ?>
                            <div class="bottomleftbox ">
                             
                                <div class="description-reviews" >
                                  <h3><?php echo $this->__('Description') ?></h3> 
                                    <div class="clsdescription"><?php echo $renderDescription; ?></div>
                                </div>

                                <div class="bottom_left_newouter">
                                <script type="text/javascript">/* <![CDATA[ */
                                document.write('<fb:comments  width="460"  num_posts="10"  xid="<?php echo $_product->getId(); ?>" href="<?php echo $URL = $productUrl; ?>"></fb:comments>')
                                /* ]]> */</script>
                                </div>
                            </div>
                            <div class="bottomrightbox">
                             <h5>Company name</h5>
                                <div class="company-details">
                                   
                                    <?php if (!empty($website)) {?>
                                        <a href="<?php echo 'http://'.$website; ?>" target="_blank" class="website"> <?php echo $website; ?></a>
                                    <?php } ?>
                                     <?php if (!empty($map)) { ?>
                                        <div class="map_grid"><?php echo $map; ?></div>
                                    <?php } ?>
                                    <strong><?php echo $this->__('The Company'); ?></strong>
                                    <address><?php echo $customersite; ?></address>
                                    <?php if (!empty($phone)) { ?>
                                    <p class="company_phone"><?php echo $phone; ?></p>
                                    <?php } ?>                                                                    
                                                                   
                                </div>
                            </div>
                        <?php endif; ?>
                            </div>
                        </div>
					<div id="custom_options" style="display: none;">
                    <div id="custom_options_top">
                        <h3><?php echo $this->__('Choose your deal:'); ?></h3>
						 <a  class="close custom_close" href="javascript:hideCustomoptions()"> <img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" width="16" height="16" title="<?php echo $this->__('close') ?>"  /></a>
                            <?php
                            $attVal = $_product->getOptions();
                            if (sizeof($attVal)) {
                                foreach ($attVal as $optionVal) {
                                    echo '<h4>'. $optionVal->getTitle() . '</h4>'; ?>
                        <div class="left_anchore"></div>
                        <ul class="deal_options" id="subdeal_content">
                            <?php $options_count=0; ?>
                            <?php foreach ($optionVal->getValues() as $valuesKey => $valuesVal) { ?>
                            <li class="<?php if(!($options_count%2==0)){ echo 'shade_option';} ?>" >
                                <form action="<?php echo Mage::getBaseUrl(); ?>checkout/cart/add/" method="post" id="product_addtocart_form_<?php echo $valuesVal->getId() ?>"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                                    <fieldset class="no-display">
                                        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                                        <input type="hidden" name="related_product" id="related-products-field" value="" />
                                    </fieldset>
                                    <div class="clearfix">
                                        <div class="description" style="display: block;"><a href="javascript:void(0)" onclick="productAddToCartForm<?php echo $valuesVal->getId() ?>.submit()"><?php echo $valuesVal->getTitle(); ?></a></div>
                                    <?php
                                    // get individual bought for custom options
                                    $qty = $this->getCustomoptionqty($_product,$valuesVal);
                                    ?>
                                    <div class="status"><?php if($_product->gettarget_number() != 0) { if($qty > $_product->gettarget_number()) echo $this->__('Over'); } ?> <?php echo $qty; ?> <?php echo $this->__('Bought'); ?></div>
                                    <input type="hidden" name="options[<?php echo $optionVal->getId(); ?>]" value="<?php echo $valuesVal->getId() ?>" />
                                    <input name="qty" type="hidden" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) == null ? 1 : $this->getMinimalQty($_product) ?>"/>
                                    <?php
                                    if($_product->getSpecialPrice()) {
                                        $customPrice = $_product->getSpecialPrice();
                                    } else {
                                        $customPrice = $_product->getPrice();
                                    }
                                    if($valuesVal->getPriceType() == 'fixed') {
                                        $price = $customPrice + $valuesVal->getPrice();
                                    } else {
                                        $percent = $customPrice * ($valuesVal->getPrice()/100);
                                        $price = $customPrice + $percent;
                                    }
                                    ?>
                                    <button id="price_button" type="button" class="price_btn" style="width: auto;" onclick="productAddToCartForm<?php echo $valuesVal->getId() ?>.submit()"><?php echo Mage::helper('core')->currency($price, true, true); ?></button>
                                    <div class="clear"></div>
                                    </div>
                                </form>
                                        <script type="text/javascript">
                                            var productAddToCartForm<?php echo $valuesVal->getId() ?> = new VarienForm('product_addtocart_form_<?php echo $valuesVal->getId() ?>');
                                            productAddToCartForm<?php echo $valuesVal->getId() ?>.submit = function(){
                                                if (this.validator.validate()) {
                                                    this.form.submit();
                                                }
                                            }.bind(productAddToCartForm<?php echo $valuesVal->getId() ?>);
                                        </script>
                         </li>
                         <?php $options_count++; ?>
                                    <?php
                                    } ?>
                                </ul>
                               <?php  }
                            }
                            ?>
                            </div>
                </div>
				<?php
				$_gallery = $_product->getMediaGalleryImages();
                $currentUrl = $this->helper('core/url')->getCurrentUrl();
                $content = '&amp;';
                $customersite = $_product->getcustomersite();
                $highlight = $_product->gethightlight();
                $fineprint = $_product->getFineprint();
                $website = $_product->getCustomerWebsite();
                $map = $_product->getsitemap();
                $phone = $_product->getQuestions();
                $_description = $_product->getdescription();
				$renderDescription = $this->helper('catalog/output')->productAttribute($_product, $_description, 'description');
				?>
				<div class="clear"></div>
				<?php 
				$data = explode("-", $customersite);
				?>
				<div class="company-details">
					<div class="col-4 first">
						<span class="title-company bold">THE SELLER</span><br/>
						<?php 
						if(is_null($customersite)){
							echo "No Seller";
						}else{
							echo $data[0]; 
						}
						?>
					</div>
					<div class="col-4">
						<span class="title-company bold">SELLER REVIEW</span><br/>
						<span>SELLER REVIEW</span><br/>
					</div>
					<div class="col-4 last">
						<span class="title-company bold">LOCATION</span><br/>
						<?php 
						if(is_null($data[1])){
							echo "No Location";
						}else{
							echo $data[1]; 
						}
						?>
					</div>
					<div></div>
				</div>
				<div class="clear"></div>
				<div class="tabs">
					<!-- Radio button and lable for #tab-content1 -->
					<input type="radio" name="tabs" id="tab1" checked >
					<label class="first" for="tab1">
						<span>Product Description</span>
					</label>
				 
					<!-- Radio button and lable for #tab-content2 -->
					<input type="radio" name="tabs" id="tab2">
					<label for="tab2">
						<span>Highlights</span>
					</label>
				 
					<!-- Radio button and lable for #tab-content3 -->
					<input type="radio" name="tabs" id="tab3">
					<label for="tab3">
						<span>Fine Print</span>
					</label>
				 
					<div id="tab-content1" class="tab-content">
						<p><?php echo $renderDescription; ?></p>
					</div> <!-- #tab-content1 -->
					<div id="tab-content2" class="tab-content">
						<p><?php echo $highlight; ?></p>
					</div> <!-- #tab-content2 -->
					<div id="tab-content3" class="tab-content">
						<p><?php echo $fineprint; ?></p>
					</div> <!-- #tab-content3 -->
				</div>
				<div class="clear"></div>
				<div class="cta-section"><div class="col-8 name"><h3><?php echo $_product->getName().', Save '.$discount . '%'; ?></h3></div><div class="col-4 button">
				<?php   
				if($productQuantiy!=  '' || $productQuantiy != 0) { ?>
						<?php if($_product->getOptions()) { ?>                                
								<a onclick="showCustomoptions();" href='JavaScript:void(0);' id="scriptbuynow-<?php echo $count; ?>" class="buynowbtn see_option small"><?php echo $this->__("See Options") ?></a>                                
						<?php } else { ?>
								<?php if($sp_price !=0){ ?>
								<a href='<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>' id="scriptbuynow-<?php echo $count; ?>" class="buynowbtn small"><?php echo $this->__("BUY NOW!") ?></a>
								<?php } else { ?>
								 <a href='<?php echo $this->helper('checkout/cart')->getAddUrl($_product); ?>' id="scriptbuynow-<?php echo $count; ?>" class="buynowbtn small"><?php echo $this->__("Free!") ?></a>
						<?php } }?>
				<?php } else { ?>
				<span class="sold_out">Sold Out</span>
				<?php } ?></div>
				</div>
				
<?php 
}
?>
<script type="text/javascript">
function switchImage(cnt){
                document.getElementById('video-'+cnt).style.display="none";
                document.getElementById('image-'+cnt).style.display="block";
                document.getElementById('switchVideo-'+cnt).style.display="block";
                document.getElementById('switchImage-'+cnt).style.display="none";
                document.getElementById('featured-'+cnt).style.display="block";
                document.getElementById('featured-'+cnt).style.width="460px";
                document.getElementById('featured-'+cnt).style.height="279px";
            }
function switchVideo(cnt){
                document.getElementById('featured-'+cnt).style.display="none";
                document.getElementById('video-'+cnt).style.display="block";
                document.getElementById('switchVideo-'+cnt).style.display="none";
                document.getElementById('switchImage-'+cnt).style.display="block";               
            }
            function getFlashMovie(movieName)
            {
                var isIE = navigator.appName.indexOf("Microsoft") != -1;
                return (isIE) ? window[movieName] : document[movieName];
            }
			
</script>